### ISSUE TITLE
Type error in prism

### ISSUE THREAD

**Issue by terryjiang2020** [angular-package/angular-package#29]
After installing this and prism.js to my angular project, I got an error when I tried to compile it in aot mode: 

`../node_modules/@angular-package/prism/typings/index.d.ts:1:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'Prism' must be of type 'typeof import("D:/projectname/node_modules/@types/prismjs/index")', but here has type 'any'.

1 declare var Prism;
              ~~~~~`

Wonder if it is a bug, any help would be appreciated.

**Comment by sciborrudnicki** [comment]
Hi,

What version of prismjs do you have installed because it should work fine with that from config 1.9.0 but as I see now It is 1.20.0

@angular-package wasn't updated for so long and it's maybe going to be rewritten to use https://angular.io/guide/creating-libraries but for now, it won't be updated.

**Comment by terryjiang2020** [comment]
I am using the latest version so probably that's the problem. 

I just switch to ngx-prism and it works fine for now (but it seems don't provide dynamic highlighting). I'll be waiting for the rewritten.
